swagger: "2.0"

info:
  version: 1.0.0
  title: FACE AML APIs
  description: The Face AML API document is intended strictly for internal use only.

schemes:
  - http
host: localhost:8080
basePath: "/api"

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  basicAuth:
    type: basic

tags:
  - name: "auth"
    description: "Token generation"
  - name: "face-aml"
    description: "Access to Face AML APIs"

paths:
  /auth/token:
    post:
      security:
        - basicAuth: []
      tags:
        - "auth"
      summary: To generate an auth token.
      description: This API generated the auth token based on client ID, client Secret, user id and app key shared.
      parameters:
        - in: "body"
          name: "body"
          description: "user object that needs to be shared to generate the token."
          required: true
          schema:
            $ref: "#/definitions/Auth"
      responses:
        200:
          description: The generated jwt token.
          schema:
            type: object
            properties:
              is_error:
                type: boolean
              status_code:
                type: integer
              display_msg:
                type: string
              res_data:
                type: object
                properties:
                  token:
                    type: string
        400:
          description: Something wrong in the body.
          schema:
            $ref: "#/definitions/GenericResponse"
        401:
          description: Invalid credentials
          schema:
            $ref: "#/definitions/GenericResponse"

  /face-aml:
    post:
      tags:
        - "face-aml"
      consumes:
        - multipart/form-data
      summary: To get the face AML response
      description: This API gets the face AML response
      parameters:
        - in: formData
          name: image
          type: file
          description: "The image to be compared"
          required: true
        - in: formData
          name: name
          type: string
          required: false
          description: Description of file contents.
      responses:
        200:
          description: The generated jwt token.
          schema:
            $ref: "#/definitions/GenericResponse"
        400:
          description: Something wrong in the body.
          schema:
            $ref: "#/definitions/GenericResponse"
        401:
          description: Invalid credentials
          schema:
            $ref: "#/definitions/GenericResponse"

definitions:
  GenericResponse:
    type: object
    properties:
      is_error:
        type: boolean
      status_code:
        type: integer
      display_msg:
        type: string
    xml:
      name: "GenericResponse"
  FaceAMLRequestBody:
    type: object
    properties:
      bucket:
        type: string
      source:
        type: string
      similarity_threshold:
        type: integer
        example: 70
    xml:
      name: "FaceAMLRequestBody"
  Auth:
    type: object
    required:
      - user_id
      - password
    properties:
      user_id:
        type: string
        example: ajdfhky12o83uwkjhfi
        description: user id of the user.
      password:
        type: string
        example: ajdfhky12o83uwkjhfi
        description:  password of the user.
    xml:
      name: "Auth"